### ISSUE TITLE
ppa:touchegg/stable crashes add-apt-repository

### ISSUE THREAD

**Issue by frederikheld** [JoseExposito/touchegg#472]
### Describe the bug

I'm getting a system error on ubuntu startup. The crash report says that `/usr/bin/python3 /usr/bin/add-apt-repository ppa:touchegg/stable` returned HTTP 500.

Running `sudo apt update` a couple of minutes later did not yield any errors.

I had the same issue when I first added ppa:touchegg/stable via terminal. I ran the command again seconds later without any error.

Looks like an unstable server that is serving the package...?

### Expected behaviour

No error

### Actual behaviour

Error

### Logs

This is the relevant part of the crash report:

```
ProblemType: Crash
Date: Mon Mar 15 22:52:53 2021
ExecutablePath: /usr/bin/add-apt-repository
ExecutableTimestamp: 1611760221
InterpreterPath: /usr/bin/python3.8
ProcCmdline: /usr/bin/python3 /usr/bin/add-apt-repository ppa:touchegg/stable
[...]
PythonArgs: ['/usr/bin/add-apt-repository', 'ppa:touchegg/stable']
Traceback:
 Traceback (most recent call last):
   File "/usr/bin/add-apt-repository", line 331, in <module>
     sys.exit(0 if addaptrepo.main() else 1)
   File "/usr/bin/add-apt-repository", line 324, in main
     shortcut.add()
   File "/usr/lib/python3/dist-packages/softwareproperties/shortcuthandler.py", line 219, in add
     self.add_key()
   File "/usr/lib/python3/dist-packages/softwareproperties/shortcuthandler.py", line 391, in add_key
     if not all((self.trustedparts_file, self.trustedparts_content)):
   File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 128, in trustedparts_content
     key = self.lpppa.getSigningKeyData()
   File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 605, in __call__
     response, content = self.root._browser._request(
   File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 438, in _request
     raise error
 lazr.restfulclient.errors.ServerError: HTTP Error 500: Internal Server Error
 Response headers:
 ---
 connection: close
 content-length: 30
 content-type: text/plain
 date: Mon, 15 Mar 2021 21:52:52 GMT
 server: zope.server.http (HTTP)
 status: 500
 x-lazr-oopsid: OOPS-8b36e97be369cdc20bad7de07ba523fd
 x-powered-by: Zope (www.zope.org), Python (www.python.org)
 ---
 Response body:
 ---
 b'GPGKeyTemporarilyNotFoundError'
 ---
```

```
$ touchegg --debug

```

### Your environment

 * Version of Touchégg: v2.0.8
 * Operating System: Ubuntu 20.10
 * Desktop Environment: Gnome

**Comment by JoseExposito** [comment]
Hi, and thanks for the bug report

The PPA is hosted by launchpad.net, I guess they experimented temporary server errors.

Closing the issue as there is not much I can do.
