### ISSUE TITLE
Failed to add PPA to Ubuntu 23.04

### ISSUE THREAD

**Issue by Anifyuli** [JoseExposito/touchegg#634]
### Describe the bug

I reinstall my Ubuntu and I want to add PPA in Ubuntu 23.04, but I get failed state of adding PPA

### Expected behaviour

PPA can applied properly

### Actual behaviour

I get this from add-apt-repository
```bash
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 362, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/add-apt-repository", line 355, in main
    shortcut.add()
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuthandler.py", line 222, in add
    self.add_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuthandler.py", line 398, in add_key
    if not all((self.trustedparts_file, self.trustedparts_content)):
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 141, in trustedparts_content
    key = self.lpppa.getSigningKeyData()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 642, in __call__
    response, content = self.root._browser._request(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 484, in _request
    raise error
lazr.restfulclient.errors.ServerError: HTTP Error 500: Internal Server Error
Response headers:
---
connection: close
content-length: 30
content-type: text/plain;charset=utf-8
date: Wed, 09 Aug 2023 13:53:33 GMT
server: gunicorn
status: 500
x-lazr-oopsid: OOPS-e7586037f46c4cb5e6608da5782aabf9
x-powered-by: Zope (www.zope.org), Python (www.python.org)
x-request-id: 6da8db3b-beb4-4988-8a99-236d33c6d779
x-vcs-revision: bf9286d3211228b39fb5e1bc0ab1d4880a464154
---
Response body:
---
b'GPGKeyTemporarilyNotFoundError'
---
```

### Logs

Touchegg can't installed, so I can't tracing it bug. I get problem in adding PPA

```
$ touchegg --debug

```

### Your environment

 * Version of Touchégg: Latest version, I guess
 * Operating System: Ubuntu 23.04
 * Desktop Environment: Gnome 44.3

**Comment by JoseExposito** [comment]
Hi!

There is a pull request, that is not merged yet, but tries to explain this issue:
https://github.com/JoseExposito/touchegg/pull/625#issuecomment-1656349226

Hopefully that command fixes your issue. Waiting a bit should do the trick as well, sometimes the PPA server fails.

**Comment by Anifyuli** [comment]
I get this error from APT, and I use that trick again after many times to using it and I fail to sign PPA key. You can look my mean like this
```shell
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C0FCE32AF6B96252 
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.hknToNTt5M/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys C0FCE32AF6B96252
gpg: keyserver receive failed: No data
anifyuli@ThinkPad-X280:~ 
$ sudo apt update
Hit:1 https://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 https://packages.microsoft.com/repos/code stable InRelease               
Hit:3 http://archive.ubuntu.com/ubuntu lunar InRelease                         
Hit:4 https://mirror.sg.gs/ubuntu lunar InRelease                              
Get:5 http://archive.ubuntu.com/ubuntu lunar-updates InRelease [109 kB]        
Get:6 https://ppa.launchpadcontent.net/touchegg/stable/ubuntu lunar InRelease [18,1 kB]
Err:6 https://ppa.launchpadcontent.net/touchegg/stable/ubuntu lunar InRelease  
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C0FCE32AF6B96252
Get:7 http://archive.ubuntu.com/ubuntu lunar-backports InRelease [99,8 kB]
Get:8 http://archive.ubuntu.com/ubuntu lunar-security InRelease [109 kB]
Get:9 http://archive.ubuntu.com/ubuntu lunar-updates/main amd64 DEP-11 Metadata [81,2 kB]
Get:10 http://archive.ubuntu.com/ubuntu lunar-updates/universe amd64 DEP-11 Metadata [52,7 kB]
Get:11 http://archive.ubuntu.com/ubuntu lunar-backports/universe amd64 DEP-11 Metadata [13,2 kB]
Get:12 http://archive.ubuntu.com/ubuntu lunar-security/main amd64 DEP-11 Metadata [7.404 B]
Get:13 http://archive.ubuntu.com/ubuntu lunar-security/universe amd64 DEP-11 Metadata [6.580 B]
Reading package lists... Done                 
W: GPG error: https://ppa.launchpadcontent.net/touchegg/stable/ubuntu lunar InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C0FCE32AF6B96252
E: The repository 'https://ppa.launchpadcontent.net/touchegg/stable/ubuntu lunar InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

I think your PPA not saving it key. What do you think about it?

**Comment by JoseExposito** [comment]
Could you try to run `sudo add-apt-repository ppa:touchegg/stable` again, please? The PPA servers fails quite often and the key fails to be added. Re-running the command once the server is up usually fixes it. 

As a side note, I'm surprised that the keyserver is returning not found at the moment for Touchégg's key:
https://keyserver.ubuntu.com/pks/lookup?fingerprint=on&op=index&search=0x7EA12677D47B593CE22727D4C0FCE32AF6B96252

There might be having some issues...

**Comment by Anifyuli** [comment]
Yeah, I get it to after checking keyserver
> As a side note, I'm surprised that the keyserver is returning not found at the moment for Touchégg's key: https://keyserver.ubuntu.com/pks/lookup?fingerprint=on&op=index&search=0x7EA12677D47B593CE22727D4C0FCE32AF6B96252
> 
> They might be having some issues...

I still get this problem too
```shell
$ sudo add-apt-repository ppa:touchegg/stable
[sudo] password for anifyuli: 
Repository: 'deb https://ppa.launchpadcontent.net/touchegg/stable/ubuntu/ lunar main'
Description:
Latest stable version of Touchégg for all Ubuntu flavours.

Touchégg is an app that runs in the background and transform the gestures you make on your touchpad or touchscreen into visible actions in your desktop. Learn more at https://github.com/JoseExposito/touchegg
More info: https://launchpad.net/~touchegg/+archive/ubuntu/stable
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Adding deb entry to /etc/apt/sources.list.d/touchegg-ubuntu-stable-lunar.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/touchegg-ubuntu-stable-lunar.list
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 362, in <module>
    sys.exit(0 if addaptrepo.main() else 1)
                  ^^^^^^^^^^^^^^^^^
  File "/usr/bin/add-apt-repository", line 355, in main
    shortcut.add()
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuthandler.py", line 222, in add
    self.add_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/shortcuthandler.py", line 398, in add_key
    if not all((self.trustedparts_file, self.trustedparts_content)):
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 141, in trustedparts_content
    key = self.lpppa.getSigningKeyData()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 642, in __call__
    response, content = self.root._browser._request(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 484, in _request
    raise error
lazr.restfulclient.errors.ServerError: HTTP Error 500: Internal Server Error
Response headers:
---
connection: close
content-length: 30
content-type: text/plain;charset=utf-8
date: Mon, 14 Aug 2023 02:54:48 GMT
server: gunicorn
status: 500
x-lazr-oopsid: OOPS-a3631496a42b423b1048d320eab94f54
x-powered-by: Zope (www.zope.org), Python (www.python.org)
x-request-id: ce908114-d0a0-4aee-87b0-20c0f094a7d5
x-vcs-revision: fec9c6ccd5524f860061c716358085f6f6ffff7c
---
Response body:
---
b'GPGKeyTemporarilyNotFoundError'
---


```

**Comment by JoseExposito** [comment]
The key not found error should be fixed by now:
https://github.com/JoseExposito/touchegg/pull/625#issuecomment-1682730887

Hopefully this time the PPA server works...

**Comment by Anifyuli** [comment]
![image](https://github.com/JoseExposito/touchegg/assets/73734843/59a8c984-0244-4936-bbb6-8b2c1b28c485)
Yeay, I can add Touchegg PPA again, thank you very much, Mister @JoseExposito

**Comment by JoseExposito** [comment]
Cool, thankfully it finally worked :tada:
